#!/bin/sh

pip install --no-cache -r requirements.txt

{% if cookiecutter.runtime in ['cpy3', 'pypy3'] %}
python3 \
{% else %}
python \
{% endif %}
{% if cookiecutter.framework == 'twisted' %}
    -u client_tx.py \
{% else %}
    -u client_aio.py \
{% endif %}
    --url {{ cookiecutter.url }} \
    --realm {{ cookiecutter.realm }}
